# cd vào src rồi chạy câu lệnh này
# gcc client.c ./register/register.c ./auth/auth.c ./server_com/server_com.c ./login/login.c ./homepage/homepage.c ticket_detail/ticket_detail.c list/list.c ./component/component.c ./global/global.c -o client `pkg-config --cflags --libs gtk+-3.0` -lssl -lcrypto -lpthread -lm
